### PR TITLE
Login popup fixes

### LINKED ISSUE #142: No error message when precondition checks fail on backend
**Describe the bug**
When one of these checks fail:
image
A 400 error message is returned with no msg field. This is an issue because we use the msg on the front end to display what the error was.

**To Reproduce**
Send a message that fails one of the preconditions

**Expected behavior**
the returned objects should have a msg field describing what went wrong

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by SecondThread**
**Description**
Allows the login/signup popups to be closed by clicking outside of them and reopened later (thanks Emil for finding that bug). Upon further inspection, Casus doesn't actually need to be changed since filling out the form is mandatory unless you hit cancel. Also properly handles error messages when an array of errors is returned from the backend.

Resolves #142

**Type of change**
Check options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Fix or feature that would cause existing functionality to not work as expected
- [ ] This change requires a update in the design document

**Steps to Verify Functionality**
Make a bulleted/numbered list of steps to verify this feature/bugfix. Include screenshots if necessary.
- Passes flow with no errors.
- Gives errors on the front end when:
    - username too short
    - password too short
    - email not valid
    - passwords don't match (verified on front-end)

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Pulled updated master branch (if changed since branch creation) and corrected any conflicts, if any occur.

### CODE REVIEW

**Comment by blaiadam** [comment]
Got a flow error

image

**Comment by SecondThread** [comment]
hmmm, I don't? I'll look into it...
image

**Comment by blaiadam** [comment]
I didn't have the .env, but I'm trying to see if its my problem. Going to do a full clean pull.

**Comment by SecondThread** [comment]
Oh, my bad. I had changes I didn't add to the commit^

**Review by blaiadam — APPROVED** [review]
All good, just pull from master before pushing.

**Pull request merged**
