### PR TITLE
Feature/update issue templates add pr template

### LINKED ISSUE #32: Update issue templates and add pull request template
**Is your feature request related to a problem? Please describe.**
Just want to simplify the issue templates and add a pull request template.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Derplime**
Resolves #32 

Updating feature request and bug report templates and added pull request template

### CODE REVIEW

**Review by SecondThread — APPROVED** [review]
Address comments before pushing please :)

**Comment by Derplime** [comment]
> We are going to be pushing code that we know breaks things?

An example would be:
We have our API already using our current models to update/add to DB. A PR that changes the models can essentially cause the current API functionality to not work as expected. It's probably the wording on that choice that made it look weird.

**Comment by Derplime** [comment]
> Shouldn't we just update the documentation in the PR then?

I should clarify that "documentation" means the design document, and rewrite that bit.

**Comment by Derplime** [comment]
@SecondThread let me know if those replies address those well enough. I'll likely edit the files again to make the choices read clearer to not cause any confusion.

**Pull request merged**
